module Constants {
  enum {
    MESSAGE_TYPE_CURRENT_ANGLE = "MESSAGE_TYPE_CURRENT_ANGLE",
    MESSAGE_TYPE_ALL = "MESSAGE_TYPE_ALL",
  }

  enum {
    KEY_MESSAGE_TYPE = "KEY_MESSAGE_TYPE",
    KEY_MESSAGE_PAYLOAD = "KEY_MESSAGE_PAYLOAD",
  }

  enum {
    MESSAGE_PAYLOAD_POSITION_LAT = "lat",
    MESSAGE_PAYLOAD_POSITION_LNG = "lng",
    MESSAGE_PAYLOAD_SPEED = "speed",
    MESSAGE_PAYLOAD_MAX_ANGLE = "maxAngle",
    MESSAGE_PAYLOAD_ANGLE = "angle",
    MESSAGE_PAYLOAD_TIME = "time",
  }
}
